#!/bin/bash

echo "  +++  Installing necessary components in order to capybara work with Rails..."

apt-get update -qq
apt-get install -y libqt4-webkit libqt4-dev xvfb
apt-get clean

echo "  +++  Capybara components installed"
