#!/bin/bash
set -e

echo "  +++  Installing passenger..."

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
apt-get update -qq
apt-get install -y apt-transport-https

sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main > /etc/apt/sources.list.d/passenger.list'
apt-get update -qq

# install all necessary packages
apt-get install -y passenger

echo "  +++  Putting passenger script to /etc/service/passenger..."

mkdir -p /etc/service/passenger
cp /opt/passenger/run /etc/service/passenger/run
chmod +x /etc/service/passenger/run

apt-get clean
echo "  +++  Passenger has been installed"
